### PR TITLE
Use submodules instead of sys.path link

### PR DESCRIPTION
**Pull request by dd388**
How does this work for you?
`git submodule update --init --recursive` should do the trick to get the submodules.

### CODE REVIEW

**Comment by tw4l** [comment]
Hi Dianne. This seems to be breaking the install script. If I manually move Objects.py and dfxml.py to the same installation dir as the rest of the Disk Image Processor (/usr/share/ccatools/diskimageprocessor), it's not able to import. Any ideas?

**Comment by dd388** [comment]
I have an idea! More soon...

**Comment by dd388** [comment]
So ... try this out and see how it goes. It checks for the DFXML libraries, and if they don't exist (for non-BitCurator systems) the submodule gets initiated. In either way, symlinks for `dfxml.py` and `Objects.py` are made -- either to the existing libraries or the newly fetched ones. Does that then work?

**Comment by tw4l** [comment]
Looks good to me! Thank you, Dianne! 🥇 Now let me see if I can copy your work for the other tools :)

**Pull request merged**
